# permissions for end users to edit merndeployers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: merndeployer-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: merndeployment
    app.kubernetes.io/part-of: merndeployment
    app.kubernetes.io/managed-by: kustomize
  name: merndeployer-editor-role
rules:
- apiGroups:
  - cache.my.domain
  resources:
  - merndeployers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.my.domain
  resources:
  - merndeployers/status
  verbs:
  - get
